FROM brooksambrose/bench
MAINTAINER "Brooks Ambrose" brooksambrose@berkeley.edu

## create directory
run cd ~ && mkdir materials && cd materials

## clone user libraries
RUN git clone https://github.com/brooksambrose/pack-dev

## clone clique percolation data
RUN git clone https://github.com/brooksambrose/clique-percolation

## clone wok data
RUN git clone https://github.com/brooksambrose/knowledge-survival

## clone d2016 pipeline data
